name: ddaenggeurang
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.0.0
  url_launcher: ^6.3.0

  # Firebase
  firebase_core: ^4.11.0
  firebase_auth:
  cloud_firestore:
  google_sign_in: ^6.2.1

  # AI 통신
  http: ^1.2.0

  # 로컬 저장
  shared_preferences:

  # 차트
  fl_chart:

  # 알림
  flutter_local_notifications:

  # 이미지 (영수증/미션 사진 인증)
  image_picker: ^1.2.3

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.1"
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/stickers/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Icon.png" # assets 폴더에 아이콘 파일이 있어야 합니다
  min_sdk_android: 21